#! /usr/bin/env bash

echo "Select the upload repository:"
# Ask the user to select a repository
repo=$(gum choose 'testpypi' 'pypi')

# Upload to the selected repository
twine upload --repository $repo dist/*
