#! /usr/bin/env python3

# sys (needed, since the script is in a different directory)
import sys; sys.path.append('..')
# numpy
import numpy as np

# models
from acropolis.models import AnnihilationModel
# scans
from acropolis.scans import ScanParameter, BufferedScanner

# Set/Extract the decoupling temperature
Tkd = float( sys.argv[1] ) if len( sys.argv ) != 1 else 1e0

# Define the number of points
N = 200

# Perform the scan...
scan_result = BufferedScanner(  AnnihilationModel,
                                mchi    = ScanParameter(  0,   3, N),
                                a       = 0.,
                                b       = ScanParameter(-20, -10, N, fast=True),
                                tempkd  = Tkd,
                                bree    = 1.,
                                braa    = 0.
                             ).perform_scan(cores=-1)

# ...and save the results
np.savetxt('annih_pwave_Tkd_{:.0e}MeV.dat'.format(Tkd), scan_result)
