#! /usr/bin/env python3

# sys (needed, since the script is in a different directory)
import sys; sys.path.append('..')
# numpy
import numpy as np

# models
from acropolis.models import AnnihilationModel
# scans
from acropolis.scans import ScanParameter, BufferedScanner
# pprint
from acropolis.pprint import print_version

# Print version information
print_version()

# Define the number of points
N = 200

# Perform the scan...
scan_result = BufferedScanner(  AnnihilationModel,
                                mchi    = ScanParameter(  0,   3, N),
                                a       = ScanParameter(-26, -18, N, fast=True),
                                b       = 0.,
                                tempkd  = 0.,
                                bree    = 1.,
                                braa    = 0.
                             ).perform_scan(cores=-1)

# ...and save the results
np.savetxt('annih_swave.dat', scan_result)
