#! /usr/bin/env python3

# sys (needed, since the script is in a different directory)
import sys; sys.path.append('..')
# numpy
import numpy as np

# models
from acropolis.models import AnnihilationModel
# scans
from acropolis.scans import ScanParameter, BufferedScanner
# pprint
from acropolis.pprint import print_version, print_info

# Print version information
print_version()

# Set/Extract the kinetic decoupling temperature
tempkd = float( sys.argv[1] ) if len( sys.argv ) != 1 else 1e0

# Define the number of points
N = 200

# Perform the scan...
scan_result = BufferedScanner(  AnnihilationModel,
                                mchi    = ScanParameter(  0,   3, N),
                                a       = 0.,
                                b       = ScanParameter(-21, -10, N, fast=True),
                                tempkd  = tempkd,
                                bree    = 1.,
                                braa    = 0.
                             ).perform_scan(cores=-1)

# ...specify the output-file...
results_file = 'annih_pwave_Tkd_{:.0e}MeV.dat'.format(tempkd)
# ...and save the results
np.savetxt(results_file, scan_result)

# Finally, print the output-file location
print_info(
    "Results have been written to '{}'.".format(results_file)
)
