#! /usr/bin/env python3

# sys (needed, since the script is in a different directory)
import sys; sys.path.append('..')
# numpy
import numpy as np

# models
from acropolis.models import DecayModel
# scans
from acropolis.scans import ScanParameter, BufferedScanner
# pprint
from acropolis.pprint import print_version, print_info

# Print version information
print_version()

# Set/Extract the lifetime of the mediator
tau = float( sys.argv[1] ) if len( sys.argv ) != 1 else 1e7

# Define the number of points
N = 200

# Perform the scan...
scan_result = BufferedScanner(  DecayModel,
                                mphi  = ScanParameter(0, 3, 200),
                                tau   = tau,
                                temp0 = 10.,
                                n0a   = ScanParameter(-14, -3, 200, fast=True),
                                bree  = 0.,
                                braa  = 1.
                             ).perform_scan(cores=-1)

# ...specify the output-file...
results_file = 'decay_tau_{:.0e}s_aa.dat'.format(tau)
# ...and save the results
np.savetxt(results_file, scan_result)

# Finally, print the output-file location
print_info(
    "Results have been written to {}.".format(results_file)
)
