#! /usr/bin/env python3

# sys (needed, since the script is in a different directory)
import sys; sys.path.append('..')
# numpy
import numpy as np

# models
from acropolis.ext.benchmarks import BenchmarkModel1
# scans
from acropolis.scans import ScanParameter, BufferedScanner
# pprint
from acropolis.pprint import print_version, print_info

# Print version information
print_version()

# Define the number of points
N = 50

# Perform the scan...
scan_result = BufferedScanner(  BenchmarkModel1,
                                mchi   = ScanParameter(  0,   3, N),
                                delta  = 1e-8,
                                gammad = 1e-3,
                                gammav = ScanParameter(-24, -16, N)
                             ).perform_scan(cores=-1)

# ...specify the output-file...
results_file = 'data/res_annih_bm1.dat'
# ...and save the results
np.savetxt(results_file, scan_result)

# Finally, print the output-file location
print_info(
    "Results have been written to '{}'.".format(results_file)
)
